# -*- coding: utf-8 -*-
"""Image_classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o69yF-_E7u2I8nqRbeKVguLol1WeTKug
"""

!sudo apt install tesseract-ocr
!pip install pytesseract

import pytesseract
import shutil
import os
import random
try:
 from PIL import Image
except ImportError:
 import Image

image_path_in_colab='/content/drive/MyDrive/test_2_image.png'
extractedInformation = pytesseract.image_to_string(Image.open(image_path_in_colab))
print(extractedInformation)

import pytesseract
import cv2

img = cv2.imread('/content/drive/MyDrive/test_2_image.png')

print(pytesseract.image_to_string(img))

Image('/content/drive/MyDrive/image_test.jpeg')

output = reader.readtext('/content/drive/MyDrive/image_test.jpeg')

output

cord = output[-1][0]

x_min, y_min = [min(idx) for idx in zip(*cord)]

x_max, y_max = [max(idx) for idx in zip(*cord)]

image = cv2.imread('/content/drive/MyDrive/image_test.jpeg')
cv2.rectangle(image, (x_min,y_min), (x_max,y_max), (0,0,225),2)
plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RBG))

